### ISSUE TITLE
Clicking on dropdown combo list doesn't select the value.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-wizard#102]
In combo dropdown selecting list doesn't provide value in the input field.

**Comment by robstryker** [comment]
Not sure what you mean.  As far as I can tell, when i expand the combo and click on one of the elements, the text field updates. I may be misunderstanding you.

**Comment by sudhirverma** [comment]
attaching video while selecting combo box.


https://user-images.githubusercontent.com/9924513/161564293-4efd3bfd-8976-419b-8480-f1c3fa6f9bf3.mov

**Comment by robstryker** [comment]
I believe this is out of date and fixed
