### ISSUE TITLE
Add severity for validation result

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#18]
The issue https://github.com/redhat-developer/vscode-wizard/issues/5 seems implemented this idea 

But it seems that we should the proper HTML like this:

```ts
templates.push({ id: "addusernameValidation", 
                    content: "<i class=\"icon icon__error\"></i>Username must not be 'b'"});
```

IMHO, I think we should avoid writting HTML and do like this:

```ts
templates.push({ id: "addusernameValidation", 
                    content: "Username must not be 'b'"},
severity:Severity.Error);

```

**Comment by robstryker** [comment]
I agree, which is why we had this change:

* b01752d - Change validator signature to allow separation of error, warning, info, or other (4 weeks ago) <Rob Stryker>
