### ISSUE TITLE
[help wanted] Error message is splitted in a new line

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#24]
When an error message is displayed it is splitted in a new line even if there is enough place

**Comment by robstryker** [comment]
screenshot if you have one?

**Comment by angelozerr** [comment]
Yes sure:

![image](https://user-images.githubusercontent.com/1932211/119217969-13a4b700-bade-11eb-85d8-a6c031a3728d.png)

**Comment by robstryker** [comment]
Can't figure this one out. Something about the setting__input style is different than its parent div and I just can't figure it.
