### ISSUE TITLE
UI fields should be aligned

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#28]
UI fields should be aligned (like Eclipse IDE form page).

Here a screenshot of vscode-kafka cluster wizard, all fields should be aligned after the red line:

![image](https://user-images.githubusercontent.com/1932211/119222666-b452a100-baf5-11eb-8034-c7d380ce4df9.png)

like Eclipse IDE form page:

![image](https://user-images.githubusercontent.com/1932211/119222687-dc420480-baf5-11eb-8961-d8beb93d51a1.png)

**Comment by robstryker** [comment]
This patch..... um... does its best. It mostly succeeds.

**Comment by robstryker** [comment]
Still not fixed. Getting closer though (barely)

**Comment by angelozerr** [comment]
What about using  html table to manage this issue? Its perhaps old school but it should work

**Comment by robstryker** [comment]
I think I've fixed it. Let me know. 

* 190619a - Small cleanup on css (9 minutes ago) <Rob Stryker>
