### ISSUE TITLE
Manage dirty state

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#29]
In vscode-kafka context we have a form page which is loaded from a cluster data model. This form page is used to edit a cluster. It should be nice when the form page changed, manage a dirty state (in the tab like when editor text changed).

**Comment by robstryker** [comment]
Can you clarify? Not sure what you would mean. 

Form pages are very different from editors in that they can't be saved, and there's no "original" to compare to in order to figure out if it's dirty or clean. 

Can you include a screenshot of where you would like some type of 'dirty' to be declared?

**Comment by robstryker** [comment]
Since we can change the title of the webview I suppose I can add support for an isDirty situation. Good idea. Can just add a ⚫ or something as part of the title.
