### ISSUE TITLE
Dynamic wizard 

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#32]
In vscode kafka we need to manage dynamic wizard. The first page is a combo:

![image](https://user-images.githubusercontent.com/1932211/119792863-58619100-bed6-11eb-87fa-0f9d1735fb92.png)

If user select `Configure Manually` the next button should open the page:

![image](https://user-images.githubusercontent.com/1932211/119793130-9959a580-bed6-11eb-8884-44797b714599.png)

in the another case it should not open an another wizard page (it will create cluster without filling a wizard page coming from Red Hat / Kafka

**Comment by robstryker** [comment]
This is easily accomplished via the workflowManager.

In the workflow manager you can check the data map for the value of a given field, and then return varying 'next' and 'previous' pages given the state of the map.

**Comment by robstryker** [comment]
https://github.com/robstryker/vscode-wizard/blob/withActivator/src/Sample.ts#L402

**Comment by robstryker** [comment]
If i understand your usecase correctly, if the user selects the first option, a second page should show. If the user selects the second option,  'back' and 'next' should be disabled (there is no second page) and only 'finish' should be enabled?  This is easily accomplished.

**Comment by robstryker** [comment]
Doable and demonstrated in sample
