### ISSUE TITLE
Body section should be white

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#35]
I'm using section to group fileds (nice feature!). IMHO I think section body should be white because we have the impression that fields are disabled:

![image](https://user-images.githubusercontent.com/1932211/121155700-58538080-c848-11eb-8def-d3eb60d94719.png)

**Comment by robstryker** [comment]
Fixed by https://github.com/redhat-developer/vscode-wizard/pull/37
