### ISSUE TITLE
Configure wizard page definition as form type

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#36]
In vscode-kafka I'm using vscode-wizard to:

 * edit a cluster, it's a form page
 * I have the intention to use vscode-wizard as wizard when we will create a new cluster

Form page means:

 * have a save button instead of having Back/Next/Finish button
 * when the save button is clicked it save the settings and it should not closed the wizard
 * when the save button is clicked it should refresh the tab with new cluster name and refresh the description too

Here a sample with BAd cluster name. When user change the cluster name and click on Save it should refresh tab, description without closing the wizard:

![image](https://user-images.githubusercontent.com/1932211/121163956-81c3da80-c84f-11eb-839c-0c84e4c31073.png)

It seems I could hack vscode-wizard to add my own save button, but perhaps refresh tab and description but I think form page can be a common usecase and my idea is give the capability to flag the wizard page definition as form with `form: true`:

```ts
 const clusterWizardDef: WizardDefinition = {
        title: `${initialClusterName}`,
        hideWizardHeader: true,
        form: true,
        pages: [
```

By flagging the page as form, it will generate a Save button and some callback to implement to refresh the tab name and the description. @robstryker what do you think about this idea?

**Comment by angelozerr** [comment]
After some though, having a form attribute is little hacky.

I think we should have 

 * a `FormDefinition` (like `WizardDefinition`)
 * rename all commons interface with Wizard without Wizard suffix (ex : `WizardPageDefinition` with `PageDefinition`)

```ts
export interface ContainerDefinition {
    title: string; // label of the tab
    workflowManager?: IWorkflowManager;
    renderer?: IPageRenderer;
    buttons?: ButtonItem[]
  }
```

WizardDefinition  could look like this:

```ts
export interface WizardDefinition extends ContainerDefinition  {
    description?: string;
    bannerIconString?: string;
    hideWizardHeader?: boolean;
    pages: PageDefinition[];
}
```

FormDefinition  could look like this:

```ts
export interface FormDefinition extends ContainerDefinition {
  body: PageDefinition;    
}
```
and PageDefinition:

```ts
export interface PageDefinition {
    id: string;
    title?: string;
    description?: string;
    hidePageHeader?: boolean;
    fields: (PageFieldDefinition | PageSectionDefinition)[];
    validator?: WizardPageValidator;
  }
```

**Comment by robstryker** [comment]
So, I think this sample provides everything you want (short of changing all the api). 

https://github.com/robstryker/vscode-wizard-example-extension/blob/master/src/Sample.ts#L303

I believe I can make a new wizard class that provides a nice wrapper with sensible defaults for some of this, but, I'll need to consider how people might want the titles to change based on a data field.
