### ISSUE TITLE
hideWizardHeader=false doesn't remove HTML content

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#38]
hideWizardHeader=false doesn't remove HTML content (although it should according to the code). There is an extra space:

![image](https://user-images.githubusercontent.com/1932211/121328427-9ae28f00-c914-11eb-8669-374279cf51c4.png)

**Comment by robstryker** [comment]
Seems to be a succession of borders and small spaces adding up. 

I welcome assistance if any is to be offered ;)

**Comment by angelozerr** [comment]
After some tests, if we want to remove this extra spaces:

 * when hideWizardHeader=true, it should set the display to for the proper div (`<div id="wizardHeader" style="display:none;">`)
 * style.css defines a margin for `.container`(`margin: 1em auto;`), could we remove this CSS declaration?

Please note that hideWizardPageHeader=true should set display to none for the proper div (`<div id="wizardPageHeader" style="display:none;">`)

Here the result:

before:

![image](https://user-images.githubusercontent.com/1932211/122075003-0091b800-cdfa-11eb-97ce-3e05ecf3ebb8.png)

after:

![image](https://user-images.githubusercontent.com/1932211/122074885-e35ce980-cdf9-11eb-9383-42f977895680.png)
