### ISSUE TITLE
Size problem of UI

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-wizard#58]
The vscode wizard display page with a given `width` which causes some trouble like:

 * when a combo contains a long item, it is cutted:

![image](https://user-images.githubusercontent.com/1932211/124143583-86b12e00-da8b-11eb-9343-b636141278eb.png)

 * error message which is wrapped: 

![image](https://user-images.githubusercontent.com/1932211/124295414-196bce80-db59-11eb-9c26-ae0d0ec0c262.png)

 * label which is wrapped:

![image](https://user-images.githubusercontent.com/1932211/124295609-533cd500-db59-11eb-86c6-63d6ada2b224.png)

**Comment by robstryker** [comment]
I changed from col-md-10 to col-md-11.  Hopefully this should help.

**Comment by robstryker** [comment]
Closing issue. Let me know if this has fixed anything. Or if I need to cut a release.
