### ISSUE TITLE
Expand blocks to the right

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-wizard#72]
Using vscode-wizard 0.2.15, I'm still seeing some lost space on the right of the wizard page
<img width="1190" alt="Screenshot 2021-07-15 at 15 10 57" src="https://user-images.githubusercontent.com/148698/125794487-500ab4b3-002b-4f7a-a5eb-71bf2976bd56.png">

The main body content should expand (to blue section)
The inner blocks should expand too (to pink section)

**Comment by robstryker** [comment]
I believe we recently expanded this further to the right
