### ISSUE TITLE
Validator with fieldRefresh causes textbox to lose focus after each keystroke

### ISSUE THREAD

**Issue by k-jay-c** [redhat-developer/vscode-wizard#74]
I have a form with various child fields in a section.  Depending on the value of a combo box, the other fields are enabled/disabled in the validator.

One side effect I've noticed is that when I try and edit a field which is being enabled/disabled by validator, the textbox loses focus after each keystroke.

Please see snippets of the form and validator code below.

```typescript
					{	id: "pythonSection",
						label: "Python Details",
						childFields: [
						{
							id: "addPythonModule",
							label: "Add Python Module?",
							description: "Select if Python module should also be added for this Service Point",
							type: "checkbox",
							initialValue: "true"
						},
						{
							id: "pythonModule",
							label: "Python Module",
							description: "If Python Module is required, please select name of python module",
							type: "combo",
							initialValue: "Create New",
							optionProvider: ():string[] => {
								const ret: string[] = [];
								mods.push('Create New');
								mods.forEach((val) =>{
									ret.push(val);
								});
								
								return [... new Set(ret)];
							}
						},
						{
							id: "newPythonModuleName",
							label: "Python Module Name",
							description: "Name of new Python Module if creating a new Module.",
							type: "textbox",
							placeholder: "package.moduleName",
						},
						{
							id: "pythonComponentName",
							label: "Component Name",
							description: "Component Name, added to package-meta-data.xml",
							placeholder: "main",
							type: "textbox"
						},
						{
							id: "pythonMainClassName",
							label: "Main Class name used as entry point",
							description: "Main Class Name",
							placeholder: "Main",
							type: "textbox"
						},
						{
							id: "pythonServiceClassName",
							label: "Service CB Class",
							description: "Service Callback class",
							placeholder: "ServiceCallback",
							type: "textbox"
						}]
					}
```

Validator:
```typescript
				validator: (parameters:any, previousParams: any) => {
					console.log("validating");
					const m : Map<string,FieldDefinitionState> = new Map();
					const pmod = parameters.addPythonModule;
					m.set("pythonModule", {enabled: pmod});
					const pfen = parameters.pythonModule == 'Create New';
					m.set("newPythonModuleName", {enabled: pfen && pmod});
					m.set("pythonComponentName", {enabled:pfen && pmod});
					m.set("pythonMainClassName", {enabled:pfen && pmod});
					m.set("pythonServiceClassName", {enabled:pmod});
					return { items: [], fieldRefresh: m};
				},

```

**Comment by robstryker** [comment]
Hi! 

If you can send me a minimal project or even just a standalone functional snippet demonstrating the ~~full~~ minimal wizard definition needed to replicate, along with opening the wizard, which replicates the issue, I'd be happy to take a look and see what I can do. 

I know we do have some stuff dealing with focussed widgets (added when I was on vacation) but my understanding is that validation is not entering that part of the code, at least from what I can see. Your experience clearly proves me wrong, so I'd need to trace through.

**Comment by robstryker** [comment]
As an idea, it's possible that the reason you're losing focus is not the new focus logic that was added, but rather that the widget you are modifying is being rewritten entirely because of the returned enablement values. 

The validator is given a list of the current values on the page, as well as the previous values on the page. You could iterate through them to see which ones have changed, and only set enablement when you know 100% that the 'master' control is the one being changed. In our sample, we have the following code:

```
            validator: (parameters:any, previousParams: any) => {
                console.log("validating");
                if( parameters.over18 !== previousParams.over18) {
                    const m : Map<string,FieldDefinitionState> = new Map();
                    m.set("actualAge", {enabled: parameters.over18});
                    m.set("awesome", {enabled: parameters.over18});
                    return { items: [], fieldRefresh: m};
                }
                return { items: [], fieldRefresh: new Map() };
            },
```

In the above example, we're only returning changes to enablement for fields when we know the enablement should be changed. For example, when your COMBO is the one that had a changed value, THEN you set enablement on the dependent controls. When its the dependent controls being changed, we should not be updating enablement on the dependent controls.

I hope this makes sense.

**Comment by angelozerr** [comment]
@robstryker I have the same problem in vscode-kafka, but it' sperhaps because that I update on each validate the enabled state https://github.com/jlandersen/vscode-kafka/pull/202/files#diff-ed21ddf00897fa81dd87a1e3cc68ba30ce20a7ca340013db66c548aa2fb2baffR376 ?

**Comment by robstryker** [comment]
In general you should avoid having the state of a control that the user is currently interacting with changing.

**Comment by angelozerr** [comment]
> In the above example, we're only returning changes to enablement for fields when we know the enablement should be changed. 

@robstryker it seems that you store the sate of each fields on WebView side, so you could check if widget must be redrawn or not by comparing the new state filed by user validator and the stored state and it will avoid to check

`if( parameters.over18 !== previousParams.over18) {`

**Comment by robstryker** [comment]
> @robstryker it seems that you store the sate of each fields on WebView side, so you could check if widget must be redrawn or not by comparing the new state filed by user validator and the stored state and it will avoid to check

Yes, that's what we're doing. Since each click or typed letter will cause a validation, we store the most recent map for comparison agianst the incoming map. 

You should never redraw widgets unless you have to. 

@k-jay-c let me know if this helps you or if we should close the issue or what.

**Comment by angelozerr** [comment]
@robstryker I have a draft PR https://github.com/redhat-developer/vscode-wizard/pull/79 for this issue.

**Comment by k-jay-c** [comment]
> > @robstryker it seems that you store the sate of each fields on WebView side, so you could check if widget must be redrawn or not by comparing the new state filed by user validator and the stored state and it will avoid to check
> 
> Yes, that's what we're doing. Since each click or typed letter will cause a validation, we store the most recent map for comparison agianst the incoming map.
> 
> You should never redraw widgets unless you have to.
> 
> @k-jay-c let me know if this helps you or if we should close the issue or what.

I will try this tomorrow and if the issue still persists, will aim to recreate the issue in a smaller isolated package and share.

**Comment by angelozerr** [comment]
@k-jay-c with my PR https://github.com/redhat-developer/vscode-wizard/pull/79 you should avoid checking the enabled state changes like @robstryker suggsted and you should keep your code like you have written.

**Comment by k-jay-c** [comment]
> @k-jay-c with my PR #79 you should avoid checking the enabled state changes like @robstryker suggsted and you should keep your code like you have written.

@angelozerr @robstryker - am I able to download the version with this update to test?  If not, you can download the attached package to reproduce the issue.

[vscode-wizard-example-kjay.zip](https://github.com/redhat-developer/vscode-wizard/files/6855945/vscode-wizard-example-kjay.zip)

Steps to reproduce:

1. Launch the wizard by executing the command "Issue 73 and 74 reproduction"
2. Enter a service point ID
3. Ensure "Add Python Module" is checked and "Python Module" has "Create New" selected
4. Try entering a value in "Python Module Name" field

Regards,
Jay.

**Comment by angelozerr** [comment]
@k-jay-c `vscode-wizard 0.2.18` has been released (@robstryker  thanks for the release) , please try it and give us feedback. Thanks!

**Comment by k-jay-c** [comment]
@angelozerr @robstryker - thank you for the update and great support.  I can confirm that issue is now resolved.
