### ISSUE TITLE
[Help Wanted] Show more contrast between enabled / disabled buttons

### ISSUE THREAD

**Issue by robstryker** [redhat-developer/vscode-wizard#8]
1) buttons enabled / disabled contrast
The button bar might need more color contrasts to show the enabled vs disabled

2) Section arrows
Investigate whether the arrows should be reversed.

**Comment by robstryker** [comment]
re: 2:   vscode uses sideways facing carats for closed, and downward facing for expanded.

**Comment by robstryker** [comment]
Spoke with Josh about whether chevron should represent the state the section currently is in (expanded vs collapsed) or if it should represent what clicking it will do (ie the state it WILL be in if you click it). 

Josh said he felt the current implementation felt more natural than the opposite. So, I don't think I'll be making changes to this part here.

**Comment by robstryker** [comment]
So... apparently I suck at UI and can't seem to make the style sheet show contrast better without it being ugly as hell. Any CSS fans, feel free to come help ;)

**Comment by robstryker** [comment]
This is the file that needs work ;)

https://github.com/redhat-developer/vscode-wizard/blob/master/pages/shared/style.css

**Comment by angelozerr** [comment]
@robstryker I had worked to improve buttons to have the same look than vscode:

![image](https://user-images.githubusercontent.com/1932211/126455942-7fe9b53d-29a3-47aa-83e9-410f00652eeb.png)

and color changes when theme changed too:

![image](https://user-images.githubusercontent.com/1932211/126456109-189f9fac-e2f2-42a9-a906-3d61738a6c51.png)

If you like, perhaps you could close this issue?

**Comment by robstryker** [comment]
Closing as complete. Thanks!
