### ISSUE TITLE
Add support for Multi-select list

### ISSUE THREAD

**Issue by k-jay-c** [redhat-developer/vscode-wizard#86]
Usecase here could be including a list of standard libraries in your project.

There are 2 options.

Option 1 - Have a single list with the ability to select several items in the list.  Normally this is done by holding CTRL and selecting mutliple items.  If the list is not big, this can work well.  If the list is large, option 2 is more desirable.

Option 2 - Have 2 lists side-by-side (left list and right list) and be able to move the available items (left list) into an import list (right list)

**Comment by robstryker** [comment]
I've implemented option 1 for now. I realize option 2 might be required one day, but I didn't have it in me to design that right now.
