### ISSUE TITLE
vscode wizard sample does not load

### ISSUE THREAD

**Issue by ahamid** [redhat-developer/vscode-wizard#92]
I was trying vscode-wizard for the first time and noticed there was a problem generating/loading the wizard webview, so I built and loaded up the sample vscode-wizard-extension and am seeing the same issue: 404 loading the webview resources.

![vscode-wizard-extension-error](https://user-images.githubusercontent.com/77031/141030283-1fda0b58-92b2-44a0-98b0-a56169290f6b.png)

![vscode-version](https://user-images.githubusercontent.com/77031/141030282-7a9fc512-eb14-4a14-acd1-a3c4b12a55e3.png)

A recent change in vscode perhaps (I notice the vscode-wizard-extension is set to vscode engine level of 1.52)?

**Comment by angelozerr** [comment]
> A recent change in vscode perhaps

Indeed since last version of vscode ther eis this problem, we have similar problem in https://github.com/jlandersen/vscode-kafka/issues/211

**Comment by ahamid** [comment]
Appears to be fixed with `0.2.21`, thanks @robstryker

**Comment by robstryker** [comment]
Sorry for not responding, but thanks so much for opening the bug!

Yeah, vscode really changed the security policies and i had to fix how we accessed resources.
