### ISSUE TITLE
Combo dropdown list displays data somewhere else.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-wizard#93]
Attaching an image to show the dropdown list displays data somewhere else. It should display the list of data below the combo box.

<img width="875" alt="Screenshot 2022-03-09 at 5 41 17 PM" src="https://user-images.githubusercontent.com/9924513/157505544-18b5c7b6-5404-417a-9b0d-32821aed17e9.png">

**Comment by robstryker** [comment]
I believe this is out of date and we fixed it
