### ISSUE TITLE
radio button doesn't display properly in UI.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-wizard#94]
<img width="471" alt="Screenshot 2022-03-14 at 12 25 45 AM" src="https://user-images.githubusercontent.com/9924513/158074865-c38c0ce6-fd7c-4acc-8694-1e092feb6872.png">

And in child field radio select both options
<img width="972" alt="Screenshot 2022-03-14 at 1 38 53 AM" src="https://user-images.githubusercontent.com/9924513/158077229-9b10b966-27d3-46c3-9393-12af4fd40e5e.png">

**Comment by robstryker** [comment]
Replicated.
