### ISSUE TITLE
Selecting radio button also display value which is not selected.

### ISSUE THREAD

**Issue by sudhirverma** [redhat-developer/vscode-wizard#95]
<img width="471" alt="Screenshot 2022-03-14 at 12 25 45 AM" src="https://user-images.githubusercontent.com/9924513/158146564-a7113b35-112b-48e0-a656-1d56962139cf.png">

As shown in the image if I select the Remote option and then I select the Local option. It displays both (local and remote) values in  `canFinish` data parameter.

**Comment by robstryker** [comment]
Replicated this issue.

**Comment by robstryker** [comment]
Fixed by https://github.com/redhat-developer/vscode-wizard/commit/b480c91d87a414b74762ca0911a61d21901a0788
